apiVersion: v1
kind: Secret
metadata:
  name: {{ template "nginx.fullname" . }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "nginx.name" . }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  password: {{ b64enc "secret" }}
  username: {{ b64enc "user1" }}

